// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission.proto

/*
Package permission is a generated protocol buffer package.

It is generated from these files:
	permission.proto

It has these top-level messages:
	LoginWithUserNameRequest
	LoginWithUserIDRequest
	LoginReply
	QueryUserMenusRequest
	QueryUserMenusReply
*/
package permission

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 使用用户名和密码登录请求参数
type LoginWithUserNameRequest struct {
	// 用户名
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	// 用户密码(明文)
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginWithUserNameRequest) Reset()                    { *m = LoginWithUserNameRequest{} }
func (m *LoginWithUserNameRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginWithUserNameRequest) ProtoMessage()               {}
func (*LoginWithUserNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginWithUserNameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginWithUserNameRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 使用用户ID和密码登录请求参数
type LoginWithUserIDRequest struct {
	// 用户名
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	// 用户密码(明文)
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginWithUserIDRequest) Reset()                    { *m = LoginWithUserIDRequest{} }
func (m *LoginWithUserIDRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginWithUserIDRequest) ProtoMessage()               {}
func (*LoginWithUserIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginWithUserIDRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginWithUserIDRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 用户登录之后的响应参数
type LoginReply struct {
	// 用户ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	// 用户名
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	// 真实姓名
	Realname string `protobuf:"bytes,3,opt,name=realname" json:"realname,omitempty"`
	// 机构代码
	OrgId string `protobuf:"bytes,4,opt,name=org_id,json=orgId" json:"org_id,omitempty"`
	// 用户类型编号
	TypeCode string `protobuf:"bytes,5,opt,name=type_code,json=typeCode" json:"type_code,omitempty"`
	// 用户状态(0:停用 1:启用)
	Status int32 `protobuf:"varint,6,opt,name=status" json:"status,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReply) GetRealname() string {
	if m != nil {
		return m.Realname
	}
	return ""
}

func (m *LoginReply) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *LoginReply) GetTypeCode() string {
	if m != nil {
		return m.TypeCode
	}
	return ""
}

func (m *LoginReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// 查询用户的功能菜单请求参数
type QueryUserMenusRequest struct {
	// 用户ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	// 系统编码
	SystemCodes []string `protobuf:"bytes,2,rep,name=system_codes,json=systemCodes" json:"system_codes,omitempty"`
}

func (m *QueryUserMenusRequest) Reset()                    { *m = QueryUserMenusRequest{} }
func (m *QueryUserMenusRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryUserMenusRequest) ProtoMessage()               {}
func (*QueryUserMenusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueryUserMenusRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *QueryUserMenusRequest) GetSystemCodes() []string {
	if m != nil {
		return m.SystemCodes
	}
	return nil
}

// 查询用户的功能菜单响应参数
type QueryUserMenusReply struct {
	Results []*QueryUserMenusReply_FuncMenu `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *QueryUserMenusReply) Reset()                    { *m = QueryUserMenusReply{} }
func (m *QueryUserMenusReply) String() string            { return proto.CompactTextString(m) }
func (*QueryUserMenusReply) ProtoMessage()               {}
func (*QueryUserMenusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QueryUserMenusReply) GetResults() []*QueryUserMenusReply_FuncMenu {
	if m != nil {
		return m.Results
	}
	return nil
}

// 动作
type QueryUserMenusReply_Action struct {
	// 编号
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	// 名称
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *QueryUserMenusReply_Action) Reset()                    { *m = QueryUserMenusReply_Action{} }
func (m *QueryUserMenusReply_Action) String() string            { return proto.CompactTextString(m) }
func (*QueryUserMenusReply_Action) ProtoMessage()               {}
func (*QueryUserMenusReply_Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *QueryUserMenusReply_Action) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *QueryUserMenusReply_Action) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 功能菜单
type QueryUserMenusReply_FuncMenu struct {
	// 编号
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	// 名称
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// 路由类型(1内部跳转 2外部跳转)
	RouterType int32 `protobuf:"varint,3,opt,name=router_type,json=routerType" json:"router_type,omitempty"`
	// 跳转路由
	Router string `protobuf:"bytes,4,opt,name=router" json:"router,omitempty"`
	// 分级码
	LevelCode string `protobuf:"bytes,5,opt,name=level_code,json=levelCode" json:"level_code,omitempty"`
	// 菜单图标
	Icon string `protobuf:"bytes,6,opt,name=icon" json:"icon,omitempty"`
	// 菜单动作
	Actions []*QueryUserMenusReply_Action `protobuf:"bytes,7,rep,name=actions" json:"actions,omitempty"`
	// 子级菜单
	Children []*QueryUserMenusReply_FuncMenu `protobuf:"bytes,8,rep,name=children" json:"children,omitempty"`
}

func (m *QueryUserMenusReply_FuncMenu) Reset()                    { *m = QueryUserMenusReply_FuncMenu{} }
func (m *QueryUserMenusReply_FuncMenu) String() string            { return proto.CompactTextString(m) }
func (*QueryUserMenusReply_FuncMenu) ProtoMessage()               {}
func (*QueryUserMenusReply_FuncMenu) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 1} }

func (m *QueryUserMenusReply_FuncMenu) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *QueryUserMenusReply_FuncMenu) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueryUserMenusReply_FuncMenu) GetRouterType() int32 {
	if m != nil {
		return m.RouterType
	}
	return 0
}

func (m *QueryUserMenusReply_FuncMenu) GetRouter() string {
	if m != nil {
		return m.Router
	}
	return ""
}

func (m *QueryUserMenusReply_FuncMenu) GetLevelCode() string {
	if m != nil {
		return m.LevelCode
	}
	return ""
}

func (m *QueryUserMenusReply_FuncMenu) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *QueryUserMenusReply_FuncMenu) GetActions() []*QueryUserMenusReply_Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *QueryUserMenusReply_FuncMenu) GetChildren() []*QueryUserMenusReply_FuncMenu {
	if m != nil {
		return m.Children
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginWithUserNameRequest)(nil), "permission.LoginWithUserNameRequest")
	proto.RegisterType((*LoginWithUserIDRequest)(nil), "permission.LoginWithUserIDRequest")
	proto.RegisterType((*LoginReply)(nil), "permission.LoginReply")
	proto.RegisterType((*QueryUserMenusRequest)(nil), "permission.QueryUserMenusRequest")
	proto.RegisterType((*QueryUserMenusReply)(nil), "permission.QueryUserMenusReply")
	proto.RegisterType((*QueryUserMenusReply_Action)(nil), "permission.QueryUserMenusReply.Action")
	proto.RegisterType((*QueryUserMenusReply_FuncMenu)(nil), "permission.QueryUserMenusReply.FuncMenu")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Permission service

type PermissionClient interface {
	// 使用用户名和密码登录
	LoginWithUserName(ctx context.Context, in *LoginWithUserNameRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// 使用用户ID和密码登录
	LoginWithUserID(ctx context.Context, in *LoginWithUserIDRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// 查询用户的功能菜单
	QueryUserMenus(ctx context.Context, in *QueryUserMenusRequest, opts ...grpc.CallOption) (*QueryUserMenusReply, error)
}

type permissionClient struct {
	cc *grpc.ClientConn
}

func NewPermissionClient(cc *grpc.ClientConn) PermissionClient {
	return &permissionClient{cc}
}

func (c *permissionClient) LoginWithUserName(ctx context.Context, in *LoginWithUserNameRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/permission.Permission/LoginWithUserName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) LoginWithUserID(ctx context.Context, in *LoginWithUserIDRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/permission.Permission/LoginWithUserID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) QueryUserMenus(ctx context.Context, in *QueryUserMenusRequest, opts ...grpc.CallOption) (*QueryUserMenusReply, error) {
	out := new(QueryUserMenusReply)
	err := grpc.Invoke(ctx, "/permission.Permission/QueryUserMenus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Permission service

type PermissionServer interface {
	// 使用用户名和密码登录
	LoginWithUserName(context.Context, *LoginWithUserNameRequest) (*LoginReply, error)
	// 使用用户ID和密码登录
	LoginWithUserID(context.Context, *LoginWithUserIDRequest) (*LoginReply, error)
	// 查询用户的功能菜单
	QueryUserMenus(context.Context, *QueryUserMenusRequest) (*QueryUserMenusReply, error)
}

func RegisterPermissionServer(s *grpc.Server, srv PermissionServer) {
	s.RegisterService(&_Permission_serviceDesc, srv)
}

func _Permission_LoginWithUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginWithUserNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).LoginWithUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/LoginWithUserName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).LoginWithUserName(ctx, req.(*LoginWithUserNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_LoginWithUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginWithUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).LoginWithUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/LoginWithUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).LoginWithUserID(ctx, req.(*LoginWithUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_QueryUserMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserMenusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).QueryUserMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/QueryUserMenus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).QueryUserMenus(ctx, req.(*QueryUserMenusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Permission_serviceDesc = grpc.ServiceDesc{
	ServiceName: "permission.Permission",
	HandlerType: (*PermissionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginWithUserName",
			Handler:    _Permission_LoginWithUserName_Handler,
		},
		{
			MethodName: "LoginWithUserID",
			Handler:    _Permission_LoginWithUserID_Handler,
		},
		{
			MethodName: "QueryUserMenus",
			Handler:    _Permission_QueryUserMenus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "permission.proto",
}

func init() { proto.RegisterFile("permission.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x6b, 0xa7, 0x71, 0xe2, 0x09, 0xe2, 0xb0, 0xa8, 0xc1, 0x0a, 0x42, 0x4d, 0x2d, 0x84,
	0x7c, 0x15, 0xa1, 0xf2, 0x02, 0x40, 0x2b, 0xa4, 0x48, 0x94, 0xc3, 0x96, 0xc3, 0x65, 0x64, 0xec,
	0x51, 0x6a, 0xc9, 0xf1, 0x9a, 0x9d, 0x35, 0xc8, 0xaf, 0xc0, 0x83, 0x20, 0x71, 0xcf, 0x03, 0xa2,
	0xdd, 0xb5, 0x4d, 0xda, 0xd0, 0x84, 0xde, 0xed, 0x3f, 0xe3, 0xf9, 0x76, 0xe7, 0x1f, 0x8d, 0xe1,
	0x6e, 0x89, 0x72, 0x95, 0x11, 0x65, 0xa2, 0x98, 0x95, 0x52, 0x28, 0xc1, 0xe0, 0x6f, 0x24, 0xe4,
	0x10, 0xbc, 0x16, 0xcb, 0xac, 0xf8, 0x9c, 0xa9, 0x8b, 0x8f, 0x84, 0xf2, 0x4d, 0xbc, 0x42, 0x8e,
	0x5f, 0x2b, 0x24, 0xc5, 0x26, 0x30, 0xac, 0x08, 0x65, 0x11, 0xaf, 0x30, 0x70, 0xa6, 0x4e, 0xe4,
	0xf3, 0x4e, 0xeb, 0x5c, 0x19, 0x13, 0x7d, 0x17, 0x32, 0x0d, 0x5c, 0x9b, 0x6b, 0x75, 0x78, 0x06,
	0xe3, 0x4b, 0xcc, 0xf9, 0x69, 0x4b, 0x7c, 0x00, 0x03, 0x4d, 0x58, 0x64, 0x69, 0x03, 0xf4, 0xb4,
	0x9c, 0xa7, 0x5b, 0x71, 0xbf, 0x1c, 0x00, 0xc3, 0xe3, 0x58, 0xe6, 0xf5, 0x56, 0x46, 0xf7, 0x5c,
	0x77, 0xf3, 0xb9, 0x12, 0xe3, 0xdc, 0xe4, 0x7a, 0x36, 0xd7, 0x6a, 0x76, 0x00, 0x9e, 0x90, 0x4b,
	0xcd, 0xdb, 0x37, 0x99, 0xbe, 0x90, 0xcb, 0x79, 0xca, 0x1e, 0x82, 0xaf, 0xea, 0x12, 0x17, 0x89,
	0x48, 0x31, 0xe8, 0xdb, 0x1a, 0x1d, 0x38, 0x11, 0x29, 0xb2, 0x31, 0x78, 0xa4, 0x62, 0x55, 0x51,
	0xe0, 0x4d, 0x9d, 0xa8, 0xcf, 0x1b, 0x15, 0x9e, 0xc3, 0xc1, 0xfb, 0x0a, 0x65, 0xad, 0xdb, 0x3e,
	0xc3, 0xa2, 0xa2, 0x9d, 0x9d, 0x1f, 0xc1, 0x2d, 0xaa, 0x49, 0xe1, 0xca, 0x5c, 0x44, 0x81, 0x3b,
	0xed, 0x45, 0x3e, 0x1f, 0xd9, 0x98, 0xbe, 0x8b, 0xc2, 0xdf, 0x3d, 0xb8, 0x7f, 0x95, 0xaa, 0x9d,
	0x78, 0x09, 0x03, 0x89, 0x54, 0xe5, 0x8a, 0x02, 0x67, 0xda, 0x8b, 0x46, 0xc7, 0xd1, 0x6c, 0x6d,
	0xd6, 0xff, 0xa8, 0x98, 0xbd, 0xaa, 0x8a, 0x44, 0x4b, 0xde, 0x16, 0x4e, 0x9e, 0x82, 0xf7, 0x22,
	0x51, 0x99, 0x28, 0x18, 0x83, 0x7d, 0xd3, 0xaa, 0x7d, 0x9e, 0x39, 0xeb, 0xd8, 0x9a, 0x9d, 0xe6,
	0x3c, 0xf9, 0xe9, 0xc2, 0xb0, 0xe5, 0xfc, 0x6f, 0x11, 0x3b, 0x84, 0x91, 0x14, 0x95, 0x42, 0xb9,
	0xd0, 0x16, 0x9a, 0x11, 0xf4, 0x39, 0xd8, 0xd0, 0x87, 0xba, 0x34, 0x86, 0x5a, 0xd5, 0x0c, 0xa1,
	0x51, 0xec, 0x11, 0x40, 0x8e, 0xdf, 0x30, 0x5f, 0x1f, 0x83, 0x6f, 0x22, 0x27, 0xcd, 0x5d, 0x59,
	0x22, 0x0a, 0x33, 0x05, 0x9f, 0x9b, 0x33, 0x7b, 0x0e, 0x83, 0xd8, 0xb4, 0x44, 0xc1, 0xc0, 0xd8,
	0xf2, 0x64, 0x97, 0x2d, 0xd6, 0x01, 0xde, 0x96, 0xb1, 0x53, 0x18, 0x26, 0x17, 0x59, 0x9e, 0x4a,
	0x2c, 0x82, 0xe1, 0x0d, 0x9d, 0xed, 0x2a, 0x8f, 0x7f, 0xb8, 0x00, 0xef, 0xba, 0x2a, 0x76, 0x0e,
	0xf7, 0x36, 0x36, 0x8d, 0x3d, 0x5e, 0xe7, 0x5e, 0xb7, 0x88, 0x93, 0xf1, 0xc6, 0x57, 0xe6, 0xd2,
	0x70, 0x8f, 0xbd, 0x85, 0x3b, 0x57, 0x56, 0x8d, 0x85, 0xd7, 0x22, 0xbb, 0x3d, 0xdc, 0x02, 0xfc,
	0x04, 0xb7, 0x2f, 0xb7, 0xc7, 0x8e, 0xb6, 0xb5, 0x6e, 0x71, 0x87, 0x3b, 0xdc, 0x09, 0xf7, 0xbe,
	0x78, 0xe6, 0xd7, 0xf3, 0xec, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x80, 0x88, 0xc2, 0x8e,
	0x04, 0x00, 0x00,
}
